VAR_species_id: 1
VAR_layer_id: 1
VAR_estimated_id: 1
VAR_tabX_id: 1
VAR_management_id: 0
VAR_climate_id: 1
VAR_load_tran_id: 0
VAR_species_dict:
  '1': Pine
  '2': Spruce
  '3': Birch
  '12': Beech
VAR_species_names:
- Pine
- Spruce
- Birch
- Beech
VAR_species_codes:
- pinsy
- picab
- betpe
- fagsy
VAR_layer_names:
- Trees
- Clusters
VAR_pCROBAS_multipliers:
  '1': 1.3
  '2': 1.3
  '3': 0.6
  '12': 1
VAR_theta_max: 0.03
VAR_estimated_user:
- 3.5
- 4.5
- 6
- 7
VAR_estimated_names:
- User
- Quantile
VAR_tabX_names:
- layer
- layerAggr
VAR_management_names:
- noManagement
- managed
VAR_output_names:
- hei
- dg
- ba
- dens
- npp
- et
- vol
- mort
- inc
VAR_data_from: gitlab
VAR_climate_paths:
- data/climate/provided/historical_only_prebas_picus_sites_vpd_corrected.csv
- data/climate/provided/GFDL-ESM4_SSP370_prebas.csv
- data/climate/provided/UKESM1-0-LL_ssp370_prebas.csv
- data/climate/provided/historical_detrend_climate_data_prebas.csv
VAR_climate_names:
- historical
- GFDL-ESM4_SSP370
- UKESM1-0-LL_ssp370
- historical_detrend
VAR_nfi_sweden_paths:
- data/nfi/sweden/sorted_group_species_cIDs_speciesID11to4_basal_area.csv
- data/nfi/sweden/cluster_weighted_means_speciesID11to4.csv
PATH_soil_data: data/soil/grd5_soil_data_prebas.csv
PATH_tran: data/climate/tran/
PATH_historical_climate_data_gitlab: data/climate/provided/historical_climate_data.csv
PATH_prebas_gitlab: data/climate/provided/historical_only_prebas_picus_sites_vpd_corrected.csv
PATH_prebas_future_GFDL_ESM4_SSP370: data/climate/provided/GFDL-ESM4_SSP370_prebas.csv
PATH_prebas_future_UKESM1_0_LL_ssp370: data/climate/provided/UKESM1-0-LL_ssp370_prebas.csv
PATH_prebas_historical_detrend: data/climate/provided/historical_detrend_climate_data_prebas.csv
PATH_prebas_eobs: data/climate/extracted/eobs/leap_years_sampled_eobs_prebas.csv
PATH_nfi_sweden: data/nfi/sweden/
PATH_rdata: data/rdata/
PATH_chelsa_file_nc: chelsa_1979_2016_all_vars
PATH_chelsa_nc: data/netcdf/combined/all/chelsa_1979_2016_all_vars.nc
PATH_eobs_file_nc: eobs_1979_2022_all_vars
PATH_eobs_nc: data/netcdf/combined/all/eobs_1979_2022_all_vars.nc
PATH_eobs_var_nc: hu
PATH_eobs_folder_nc: data/netcdf/eobs_vars/hu/
PATH_sites: data/climate/provided/prebas_sites_coords.csv
SRC_multi_species: scripts/multiSiteSpecies.R
SRC_multi_layers: scripts/multiSiteLayers.R
SRC_multi_and_plots_species:
- scripts/multiSiteSpecies.R
- scripts/plotsSpecies.R
SRC_multi_and_plots_layers:
- scripts/multiSiteLayers.R
- scripts/plotsLayers.R
SRC_multi_and_outputs_species:
- scripts/multiSiteSpecies.R
- scripts/output_tables.R
SRC_multi_and_outputs_layers:
- scripts/multiSiteLayers.R
- scripts/output_tables.R
SRC_plot_tables: scripts/plot_tables.R
SRC_cluster_weighted_means: scripts/cluster_weighted_means.R
SRC_sums_means: scripts/modout_sums_and_means.R
SRC_layer_aggr: scripts/layerAggr.R
SRC_mock_run_scripts:
- scripts/mock_run_script_1.R
- scripts/mock_run_script_2.R
