# VARIABLES
VAR_species_id: 2
VAR_layer_id: 2
VAR_estimated_id: 1
VAR_tabX_id: 1
VAR_management_id: 0
VAR_climate_id: 1
VAR_species_dict:
  '1': Pine
  '2': Spruce
  '3': Birch
  '12': Beech
VAR_species_names:
- Pine
- Spruce
- Birch
- Beech
VAR_species_codes:
- pinsy
- picab
- betpe
- fagsy
VAR_layer_names:
- Trees
- Clusters
VAR_pCROBAS_multipliers:
  '1': 1.3
  '2': 1.3
  '3': 0.6
  '12': 1
VAR_theta_max: 0.03
VAR_estimated_user:
- 3.5
- 4.5
- 6
- 7
VAR_estimated_names:
- User
- Quantile
VAR_tabX_names:
- layer
- layerAggr
VAR_management_names:
- noManagement
- managed
VAR_output_names:
- hei
- dg
- ba
- dens
- npp
- et
- vol
- mort
- inc
VAR_data_from: gitlab

  

# PATHS
soilData_path: data/soil/grd5_soil_data_prebas.csv

# Climate
tranPath: data/climate/tran/
historical_climate_data_gitlab_path: data/climate/provided/historical_climate_data.csv
prebas_gitlab_path: data/climate/provided/historical_only_prebas_picus_sites_vpd_corrected.csv
prebas_future_GFDL_ESM4_SSP370: data/climate/provided/GFDL-ESM4_SSP370_prebas.csv
prebas_future_UKESM1_0_LL_ssp370: data/climate/provided/UKESM1-0-LL_ssp370_prebas.csv
prebas_historical_detrend: data/climate/provided/historical_detrend_climate_data_prebas.csv
prebas_eobs_path: data/climate/extracted/eobs/leap_years_sampled_eobs_prebas.csv
climate_paths:
- data/climate/provided/historical_only_prebas_picus_sites_vpd_corrected.csv
- data/climate/provided/GFDL-ESM4_SSP370_prebas.csv
- data/climate/provided/UKESM1-0-LL_ssp370_prebas.csv
- data/climate/provided/historical_detrend_climate_data_prebas.csv
climateNames:
- historical
- GFDL-ESM4_SSP370
- UKESM1-0-LL_ssp370
- historical_detrend

# Nfi
nfi_sweden_path: data/nfi/sweden/
nfi_sweden_paths:
- data/nfi/sweden/sorted_group_species_cIDs_speciesID11to4_basal_area.csv
- data/nfi/sweden/cluster_weighted_means_speciesID11to4.csv

# Rdata
rdata_path: data/rdata/

# Netcdf
chelsa_file: chelsa_1979_2016_all_vars
chelsa_path: data/netcdf/combined/all/chelsa_1979_2016_all_vars.nc
eobs_file: eobs_1979_2022_all_vars
eobs_path: data/netcdf/combined/all/eobs_1979_2022_all_vars.nc
eobs_var: hu
eobs_folder: data/netcdf/eobs_vars/hu/

# Sites
sites_path: data/climate/provided/prebas_sites_coords.csv

